version: '3.8'

services:
  bianxi-db:
    container_name: bianxi-database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'bianxi'
      MYSQL_ROOT_PASSWORD: 'bianxi'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ../.mysql:/var/lib/mysql
