name: Build

on:
  push:
    branches: [ main, hotfix/**, release/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant Permissions
        run: chmod +x mvnw

      - name: Maven Verify
        run: ./mvnw --batch-mode clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}