name: Docker CI with Maven

on:
  release:
    tags:
      - "bianxi-api-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Copy Jar File
        run: mv ${{ github.workspace }}/application/target/application-*-exec.jar bianxi-api-${{ github.ref_name }}.jar

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bianxi-api:${{ github.ref_name }}